### ISSUE TITLE
Unable to copy text

### ISSUE THREAD

**Issue by Bogardo** [hparton/terminal.reddit#1]
On OSX I'm unable to copy text. 
On the list page, when pressing the `cmd` button the selected text is de-selected.
On a post page, pressing `cmd + C` takes you back to the list page.

**Comment by ghost** [comment]
I also experienced this problem on Windows 10, when I hit <code>CTRL</code>, the text is de-selected.

**Comment by hparton** [comment]
Thanks for flagging that up @Bogardo, can you test that again on the live site and let me know if thats fixed for you ?

**Comment by Bogardo** [comment]
It's fixed! Thanks!
